name: build k2i for windows 386

on:
  push:
    tags:
      - k2i-*

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2

      - name: Build
        run: |
          env GOOS=windows GOARCH=386 CGO_ENABLED=0 go build -o ./k2i-windows-386 k2i.go 

      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
        with:
          tagRegex: "k2i-(.*)"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "k2i-windows-386.exe"
          body: "Release ${{ steps.tagName.outputs.tag }}"